k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_clover-dev-kubernetes_us-west1_dev-us-west1-cluster
  currentCluster: gke_clover-dev-kubernetes_us-west1_dev-us-west1-cluster
  clusters:
    gke_clover-dev-kubernetes_us-west1_dev-us-west1-cluster:
      namespace:
        active: creature-deploy-mcbranchface
        favorites:
        - creature-deploy-mcbranchface
        - security-system
        - spinnaker
        - operations
        - remote-pay-ws-server
        - microservices-demo
        - customer-engagement
      view:
        active: event
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
